---
networks:
  frontend:
    external: true
services:
  traefik:
    image: traefik:v3.2
    container_name: traefik-production
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    networks:
      - frontend
    restart: unless-stopped
