global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ERROR
  format: common
  filePath: /var/log/traefik/traefik.log

accesslog:
  format: common
  filePath: /var/log/traefik/access.log

api:
  dashboard: true
  # For production environments, consider removing `insecure: true`
  # or implementing proper security.
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

certificatesResolvers:
  production:
    acme:
      email: --------
      storage: /etc/traefik/certs/acme.json
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    swarmMode: false
